# Generated by Django 4.2.2 on 2023-06-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('profile_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('profile_img', models.ImageField(upload_to='profile_imgs')),
                ('bio', models.TextField(blank=True)),
                ('is_wallet_user', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('accept_terms', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
