# Generated by Django 4.2.2 on 2023-06-22 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_moment_options_moment_is_minted_moment_votes_and_more'),
        ('capsule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipfs_url', models.URLField()),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='moment_id', to='api.moment')),
            ],
            options={
                'unique_together': {('moment', 'ipfs_url')},
            },
        ),
    ]
